networks:
  quinly-services:
    name: quinly-services
    external: true

services:

  # Jellyfin
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    env_file:
      - jellyfin.env
    volumes:
      - jellyfin-config:/config
      - ${SERIES_FOLDER}:/data/tvshows
      - ${MOVIES_FOLDER}:/data/movies
    #group_add:
      # group of the UHD iGPU
      #- "993"
    #devices:
      # device address of the UHD iGPU
      #- /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
    networks:
      quinly-services:
        ipv4_address: 10.10.0.60

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    env_file:
      - jellyseerr.env
    volumes:
      - jellyseerr-config:/app/config
    restart: unless-stopped
    networks:
      quinly-services:
        ipv4_address: 10.10.0.61

# Request management and media discovery
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    env_file:
      - overseerr.env
    volumes:
      - overseerr-config:/config
    restart: always
    depends_on:
      - gluetun
    networks:
      quinly-services:
        ipv4_address: 10.10.0.62

  # Media server - https://github.com/plexinc/pms-docker/tree/master
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:1.40.5.8921-836b34c27-ls234

    restart: unless-stopped
    #ports:
    #  - 32400:32400/tcp
    #  - 8324:8324/tcp
    #  - 32469:32469/tcp
    #  - 1900:1900/udp
    #  - 32410:32410/udp
    #  - 32412:32412/udp
    #  - 32413:32413/udp
    #  - 32414:32414/udp
    env_file:
      - plex.env
    hostname: Mordor
    volumes:
      - plex-config:/config
      - plex-transcode:/transcode
      - ${MOVIES_FOLDER}:/movies
      - ${SERIES_FOLDER}:/tv
      - ${BOOKS_FOLDER}:/books
    #devices:
      # device address of the UHD iGPU
      #- /dev/dri/renderD128:/dev/dri/renderD128
    networks:
      quinly-services:
        ipv4_address: 10.10.0.68

  # Tautulli - Monitors, analyses and notifies about Plex
  # https://github.com/Tautulli/Tautulli
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: always
    volumes:
      - tautulli-config:/config
    depends_on:
      - plex
    env_file:
      - common.env
    networks:
      quinly-services:
        ipv4_address: 10.10.0.69

volumes:
  bazarr-config:
  jellyfin-config:
  gluetun-config:
  gluetun-port_forward:
  overseerr-config:
  plex-config:
  plex-transcode:
  tautulli-config:
  prowlarr-config:
  radarr-config:
  rreading-glasses-config:
  sonarr-config:
  qbittorrent-config:
  overseerr-temp-config:
  jellyseerr-config:
  kapowarr-db:
  suwayomi-data: