networks:
  quinly-services:
    name: quinly-services
    external: true

# Subtitles gatherer
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    env_file:
      - common.env
    volumes:
      - bazarr-config:/config
      - ${MOVIES_FOLDER}:/movies
      - ${SERIES_FOLDER}:/tv
    restart: always
    depends_on:
      - gluetun
    network_mode: service:gluetun

  # Comic / Manga manager
  kapowarr:
    container_name: kapowarr
    image: mrcas/kapowarr:latest
    volumes:
      - kapowarr-db:/app/db
      - ${BOOKS_FOLDER}:/comics-1
      - ${DOWNLOADS_FOLDER}:/app/temp_downloads
    depends_on:
      - gluetun
    networks:
      quinly-services:
        ipv4_address: 10.10.0.63

  # Manga fetcher https://github.com/Suwayomi/Suwayomi-Server-docker/blob/main/docker-compose.yml
  suwayomi: # port 4567
    image: ghcr.io/suwayomi/suwayomi-server:preview
    environment:
      - TZ=Europe/London 
      - FLARESOLVERR_ENABLED=true
      - FLARESOLVERR_URL=http://localhost:8191
    volumes:
      - suwayomi-data:/home/suwayomi/.local/share/Tachidesk
      - ${BOOKS_FOLDER}:/books
    depends_on:
      - gluetun
    network_mode: service:gluetun
    restart: on-failure:3

  flaresolverr: # port 8191
    image: ghcr.io/thephaseless/byparr:latest
    container_name: flaresolverr
    env_file:
      - common.env
    restart: unless-stopped
    depends_on:
      - gluetun
    network_mode: service:gluetun

  # VPN Connection - https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/airvpn.md
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: mediagluetun
    cap_add:
      - NET_ADMIN
    networks:
      quinly-services:
        ipv4_address: 10.10.0.64
    devices:
      - /dev/net/tun:/dev/net/tun
    #ports:
    # - 8888:8888/tcp # HTTP Proxy
    #  - 8388:8388/tcp # Shadowsocks
    #  - 8388:8388/udp # Shadowsocks
    #  - 8000:8000/tcp # HTTP Control Server
    #  - 8989:8989 # Sonarr port
    #  - 9696:9696 # Prowlarr port
    #  - 7878:7878 # Radarr port
    #  #- 5055:5055 # Overseerr port
    #  - 8787:8787 # rreading-glasses port
    #  - 8082:8082 # Qbittorrent port
    #  - 6861:6861 # Qbittorrent port
    #  - 6767:6767 # Bazarr
    #  - 34400:34400 # threadfin
    # - 8191:8191 # flaresolverr
    volumes:
      - gluetun-config:/gluetun
      - gluetun-port_forward:/tmp/gluetun/forwarded_port
    env_file:
      - gluetun.env
    restart: unless-stopped

# Indexer manager
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file:
      - prowlarr.env
    volumes:
      - prowlarr-config:/config
    depends_on:
      - gluetun
    network_mode: service:gluetun
    restart: always

  # Movies indexer
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - common.env
    volumes:
      - radarr-config:/config
      - ${MOVIES_FOLDER}:/movies
      - ${DOWNLOADS_FOLDER}:/downloads
    restart: always
    depends_on:
      - gluetun
    network_mode: service:gluetun

  # Books indexer - https://github.com/blampe/rreading-glasses
  rreading-glasses:
    image: blampe/rreading-glasses:latest
    container_name: rreading-glasses
    env_file:
      - rreading-glasses.env
    volumes:
      - rreading-glasses-config:/config
      - ${BOOKS_FOLDER}:/books
      - ${DOWNLOADS_FOLDER}:/downloads
    restart: always
    depends_on:
      - gluetun
    network_mode: service:gluetun

  # Series manager / indexer
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - common.env
    volumes:
      - ${VOLUMES_FOLDER}/sonarr/sonarr-config:/config
      - ${SERIES_FOLDER}:/tv
      - ${DOWNLOADS_FOLDER}:/downloads
    restart: always
    depends_on:
      - gluetun
    network_mode: service:gluetun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file:
      - qbittorrent.env
    volumes:
      - qbittorrent-config:/config
      - ${DOWNLOADS_FOLDER}:/downloads
      - ${MOVIES_FOLDER}:/movies
      - ${SERIES_FOLDER}:/series
    depends_on:
      - gluetun
    network_mode: service:gluetun
    restart: always