networks:
  quinly-services:
    name: quinly-services
    external: true

services: 
  etcd:
    image: quay.io/coreos/etcd:v3.4.33
    container_name: etcd
    hostname: ${ETCD_NAME}-etcd
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    volumes:
      - etcd_data:/etcd-data
    env_file:
      - .env
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      quinly-services:
        ipv4_address: ${ETCD_IP}
  
volumes:
  etcd_data: