# Use this docker-compose file to run a single etcd node
# Need to run common first to create the network

networks:
  management:
    name: management
    external: true

services: 
  etcd:
    # For other versions see https://quay.io/repository/coreos/etcd?tab=tags
    # Make sure to use the same version across all nodes in a cluster
    image: quay.io/coreos/etcd:v3.4.33
    container_name: etcd
    hostname: ${NODE_NAME}-etcd
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    env_file:
      - .env
    volumes:
      - etcd_data:/etcd-data
      - ./certs:/etc/etcd/certs:ro
    networks:
      management:
        ipv4_address: ${NODE_IP}
  
volumes:
  etcd_data: